import React from 'react';
import adbGeometry from '../../adb/characters/geometry.json';
import nemiGeometry from '../../nemi/characters/geometry.json';
import {profiles} from './profiles';
import type {Author,Expression,Gesture,Shot,Event} from './types';
import {pulse,eventStrength,lerp,smooth,steppedTime,clamp} from './motion';
type Point=number[];type Geometry=Record<string,Point[]|Point[][]>;
const geometries={adb:adbGeometry as Geometry,nemi:nemiGeometry as Geometry};
const pts=(arr:Point[])=>arr.map(p=>p.join(',')).join(' ');
const poses:Record<Gesture,[number,number,number,number]>={rest:[-12,12,10,-10],explain:[-30,26,-98,90],point:[-15,72,5,93],celebrate:[-135,135,-155,155],panic:[-64,65,-148,150],draw:[-24,35,5,-72],hold:[-36,36,54,-54],facepalm:[-16,35,0,-153]};
export function handAnchor(author:Author,gesture:Gesture,side:number,previous:Gesture=gesture,progress=1){const p=profiles[author],angles=poses[gesture].map((a,i)=>lerp(poses[previous][i],a,progress)),upper=angles[side<0?0:1]*Math.PI/180,lower=angles[side<0?2:3]*Math.PI/180;const shoulder=[side*47,-71],elbow=[shoulder[0]+Math.sin(upper)*p.armUpper,shoulder[1]+Math.cos(upper)*p.armUpper],wrist=[elbow[0]+Math.sin(lower)*p.armLower,elbow[1]+Math.cos(lower)*p.armLower];return {shoulder,elbow,wrist,angle:-lower*180/Math.PI}}
function Face({author,expression,gaze,blink,mouth}:{author:Author;expression:Expression;gaze:[number,number];blink:number;mouth:string}){
 const uid=React.useId();const p=profiles[author],wide=['shocked','screaming','destroyed'].includes(expression),narrow=['sideEye','deadpan','smug','evil'].includes(expression),angry=['angry','evil'].includes(expression),happy=expression==='happy',height=(wide?13:narrow?4:author==='adb'?8:9)*(1-blink),eyeWidth=author==='adb'?11.5:12.8;
 return <g stroke={p.ink} strokeLinecap="round" strokeLinejoin="round">{[-1,1].map(s=>{const x=s*p.eyeX,y=p.eyeY,ey=`eye-${uid}-${s}`,d=`M ${x-eyeWidth} ${y} Q ${x} ${y-height*1.9} ${x+eyeWidth} ${y} Q ${x} ${y+height*1.55} ${x-eyeWidth} ${y}`;
 return <g key={s}>{expression==='destroyed'?<path d={`M ${x-8} ${y-8} l16 16 M ${x+8} ${y-8} l-16 16`} fill="none" strokeWidth="3"/>:happy||height<1?<path d={`M ${x-12} ${y+2} Q ${x} ${y-7} ${x+12} ${y+2}`} fill="none" strokeWidth="3"/>:<><defs><clipPath id={ey}><path d={d}/></clipPath></defs><path d={d} fill="white" strokeWidth="1.5"/><g clipPath={`url(#${ey})`}><ellipse cx={x+gaze[0]*5} cy={y+gaze[1]*3} rx={wide?4.5:6.5} ry={wide?8.5:9} fill={p.iris} stroke="none"/><ellipse cx={x+gaze[0]*5} cy={y+gaze[1]*3} rx="2.6" ry="6.8" fill="#172927" stroke="none"/><circle cx={x+gaze[0]*5-2} cy={y+gaze[1]*3-3} r="2.2" fill="white" stroke="none"/><circle cx={x+gaze[0]*5+2} cy={y+gaze[1]*3+3} r="1" fill="white" stroke="none"/></g><path d={`M ${x-eyeWidth} ${y} Q ${x} ${y-height*1.9} ${x+eyeWidth} ${y}`} strokeWidth={author==='nemi'?3:2.5} fill="none"/>{author==='nemi'&&<path d={`M ${x+s*12} ${y-1} l ${s*4} -3`} strokeWidth="2.5"/>}</>}
 <path d={`M ${x-11} ${y-16+(angry?s*-4:0)} Q ${x} ${y-20+(expression==='confused'?s*5:wide?-4:0)} ${x+11} ${y-16+(angry?s*4:0)}`} strokeWidth="2.4" fill="none"/>
 </g>})}<path d={`M 1 ${p.mouthY-10} l -2 3 l3 1`} fill="none" strokeWidth="1"/>
 {['embarrassed','happy','crying'].includes(expression)&&[-1,1].map(s=><g key={s}><ellipse cx={s*28} cy={p.mouthY-3} rx="9" ry="4" fill="#ed8d83" opacity=".5" stroke="none"/><path d={`M ${s*28-4} ${p.mouthY-4} l-2 4 m5 -4 l-2 4`} stroke="#b84e48" strokeWidth=".9"/></g>)}
 {expression==='crying'&&[-1,1].map(s=><path key={s} d={`M ${s*23} ${p.eyeY+7} q -6 14 1 20 q 7 -7 -1 -20`} fill="#b3eaf4" strokeWidth="1"/>)}
 {mouth==='round'||(['shocked','screaming'].includes(expression)&&mouth==='closed')?<ellipse cx="0" cy={p.mouthY} rx={expression==='screaming'?12:6} ry={expression==='screaming'?15:7} fill="#632c36" strokeWidth="1.8"/>:mouth==='open'||mouth==='wide'||happy?<g><path d={`M -11 ${p.mouthY-3} Q 0 ${p.mouthY+2} 11 ${p.mouthY-3} Q 9 ${p.mouthY+11} 0 ${p.mouthY+10} Q -9 ${p.mouthY+11} -11 ${p.mouthY-3}`} fill="#632c36" strokeWidth="1.6"/><path d={`M -9 ${p.mouthY-2} Q 0 ${p.mouthY+1} 9 ${p.mouthY-2} L7 ${p.mouthY+2} L-7 ${p.mouthY+2}Z`} fill="white" stroke="none"/><ellipse cx="0" cy={p.mouthY+7} rx="5" ry="2.5" fill="#e58b91" stroke="none"/></g>:<path d={expression==='smug'||expression==='evil'?`M -8 ${p.mouthY} Q 2 ${p.mouthY+6} 12 ${p.mouthY-2}`:expression==='destroyed'?`M -10 ${p.mouthY+3} l4 -4 l4 4 l4 -4 l4 4 l4 -4`:['deadpan','sideEye'].includes(expression)?`M -8 ${p.mouthY} L8 ${p.mouthY}`:expression==='angry'||expression==='confused'?`M -8 ${p.mouthY+2} Q 0 ${p.mouthY-3} 8 ${p.mouthY+2}`:`M -8 ${p.mouthY} Q 0 ${p.mouthY+4} 8 ${p.mouthY}`} fill="none" strokeWidth="1.8"/>}</g>
}
export function Character({author,shot,previous,t,events,blinks,mouth='closed'}:{author:Author;shot:Shot;previous?:Shot;t:number;events:Event[];blinks:{start:number;end:number}[];mouth?:string}){
 const uid=React.useId();const p=profiles[author],g=geometries[author],isN=author==='nemi',q=shot.stepped?steppedTime(t):t,progress=smooth((q-shot.start)/.25),pose=poses[shot.gesture],prev=poses[previous?.gesture??shot.gesture],angles=pose.map((v,i)=>lerp(prev[i],v,progress));
 const accent=eventStrength(events,q,'impact')+eventStrength(events,q,'pop')*.35+eventStrength(events,q,'drop'),head=lerp(previous?.actor.headTilt??shot.actor.headTilt??0,shot.actor.headTilt??0,smooth((q-shot.start-.06)/.28));
 const hair=events.reduce((a,e)=>a+pulse(q,e.at+.055,.38)*(e.strength??1)*3,0);
 const b=blinks.find(b=>t>=b.start&&t<b.end);const blink=b?Math.sin((t-b.start)/(b.end-b.start)*Math.PI):0;
 const poly=(name:string,fill:string,sw=1.8)=><polygon points={pts(g[name] as Point[])} fill={fill} stroke={p.ink} strokeWidth={sw} strokeLinejoin="round"/>;
 const line=(arr:Point[],color:string=p.ink,w=1)=><polyline points={pts(arr)} fill="none" stroke={color} strokeWidth={w} strokeLinecap="round"/>;
 const headTransform=`translate(0 ${p.headY}) rotate(${head}) scale(${p.headScale*(1+accent*.045)} ${p.headScale*(1-accent*.035)})`;
 return <g transform={`translate(${shot.actor.x} ${shot.actor.y}) scale(${shot.actor.scale})`}>
 <ellipse cx="0" cy={p.ground+3} rx="69" ry="8" fill="#182128" opacity=".14"/>
 <g transform={`translate(0 ${p.ground}) scale(${1+accent*.012} ${1-accent*.017}) translate(0 ${-p.ground})`}>
 <g transform={headTransform}><g transform={`rotate(${hair*.35})`}>{poly('backHair',p.hairShadow,2)}</g></g>
 {isN?<g>{[-1,1].map(s=><g key={s}><path d={`M ${s*22} 34 L${s*22} 167`} stroke={p.ink} strokeWidth="20" strokeLinecap="round"/><path d={`M ${s*22} 34 L${s*22} 167`} stroke={p.skin} strokeWidth="16" strokeLinecap="round"/><path d={`M ${s*22} 143 L${s*22} 169`} stroke="#fff" strokeWidth="17"/>
 <g transform={`translate(${s*22} 168)`}>{poly(s<0?'shoeLeft':'shoeRight','#fff')}{poly(s<0?'soleLeft':'soleRight','#e4e0d8')}<path d="M -5 9 l10 3 m-10 3 l10 3" stroke={p.iris} strokeWidth="2"/></g></g>)}{poly('skirt',p.pants)}{(g.pleats as Point[][]).map((a,i)=><g key={i}>{line(a,'#132e27',1.2)}</g>)}</g>:<g>{poly('pelvis',p.pants)}{poly('legLeft',p.pants)}{poly('legRight',p.pants)}{poly('shoeLeft',p.shoes)}{poly('shoeRight',p.shoes)}{poly('soleLeft','#ede9df')}{poly('soleRight','#ede9df')}<path d="M -16 47 L-18 158 M16 47 L18 158" stroke="#c8c0b4" strokeWidth="1.2"/></g>}
 <g transform={`rotate(${shot.actor.lean??0} 0 5)`}><path d={`M -9 -117 L-10 -75 L10 -75 L9 -117`} fill={p.skin} stroke={p.ink} strokeWidth="1.6"/>
 {poly('torso',p.shirt,2)}
 {isN?<g>{poly('collar',p.shirtShadow)}<path d="M -8 -64 L-8 -44 M 8 -64 L8 -44" stroke="#f4f2ea" strokeWidth="2"/><path d="M -25 -19 Q0 -25 25 -19 L28 -4 Q0 1 -28 -4Z" fill={p.shirtShadow} stroke={p.ink} strokeWidth=".8"/><path d="M -27 -13 l-3 9 M27 -13 l3 9" stroke={p.ink} strokeWidth="1"/>{poly('strap','#29272f',.5)}{poly('bag','#2e2b32',1.5)}{poly('bagFlap','#25222a',.7)}<path d="M32 10 q-7 -7 0 -10 q7 3 0 10" fill="#f5f0d7"/></g>:<g>{poly('chest',p.skin,0)}{poly('collarLeft',p.shirtShadow,.8)}{poly('collarRight',p.shirtShadow,.8)}<path d="M0 -42 L0 19" stroke={p.shirtShadow} strokeWidth="2"/>{[-32,-10,12].map(y=><circle key={y} cx="1" cy={y} r="1.7" fill={p.ink}/>)}<path d="M -24 -55 Q-28 -20 -20 0 M24 -55 Q28 -20 20 0" fill="none" stroke={p.shirtShadow} strokeWidth="1"/></g>}
 {[-1,1].map(s=>{const upper=angles[s<0?0:1]*Math.PI/180,lower=angles[s<0?2:3]*Math.PI/180,shoulder=[s*47,-71],elbow=[shoulder[0]+Math.sin(upper)*p.armUpper,shoulder[1]+Math.cos(upper)*p.armUpper],wrist=[elbow[0]+Math.sin(lower)*p.armLower,elbow[1]+Math.cos(lower)*p.armLower];return <g key={s}><path d={`M${shoulder} L${elbow}`} stroke={p.ink} strokeWidth="27" strokeLinecap="round"/><path d={`M${shoulder} L${elbow}`} stroke={p.shirt} strokeWidth="23" strokeLinecap="round"/><path d={`M${elbow} L${wrist}`} stroke={p.ink} strokeWidth={isN?22:17} strokeLinecap="round"/><path d={`M${elbow} L${wrist}`} stroke={isN?p.shirt:p.skin} strokeWidth={isN?18:13} strokeLinecap="round"/><path d={`M${elbow[0]-8} ${elbow[1]} L${elbow[0]+8} ${elbow[1]}`} stroke={p.shirtShadow} strokeWidth="2"/>
 <g transform={`translate(${wrist[0]} ${wrist[1]}) rotate(${-lower*180/Math.PI}) scale(.8)`}>{isN?<polygon points={pts(g.hand as Point[])} fill={p.skin} stroke={p.ink} strokeWidth="1.7"/>:<path d="M-6 0 Q-8 6 -10 9 Q-10 14 -5 13 L-4 21 Q-2 25 1 20 Q4 25 5 19 Q8 23 8 16 L7 0Z" fill={p.skin} stroke={p.ink} strokeWidth="1.7"/>}{shot.gesture==='point'&&<path d="M0 14 L0 34" stroke={p.skin} strokeWidth="7" strokeLinecap="round"/>}</g></g>})}</g>
 <g transform={headTransform}>{poly('head',p.skin,1.7)}<ellipse cx="0" cy="-3" rx="15" ry="4" fill={p.skinShadow} opacity=".45"/>{[-1,1].map(s=><ellipse key={s} cx={s*(isN?40:44)} cy={isN?-37:-49} rx="5" ry="8" fill={p.skin} stroke={p.ink} strokeWidth="1.3"/>)}{isN&&<Face author={author} expression={shot.expression} gaze={shot.actor.gaze??[0,0]} blink={blink} mouth={mouth}/>}
 <g transform={`rotate(${hair*.12} 0 -80)`}>{poly('hair',p.hair,2)}<defs><clipPath id={`hair-${uid}`}><polygon points={pts(g.hair as Point[])}/></clipPath></defs><g clipPath={`url(#hair-${uid})`}>{(g.hairCreases as Point[][]).map((a,i)=><g key={i}>{line(a,p.hairLight,1.2)}</g>)}</g>{isN?<g>{poly('ahoge',p.hair,1.2)}{poly('tressLeft',p.hair,1.5)}{poly('tressRight',p.hair,1.5)}<path d="M-30 -84 Q-13 -94 3 -84 M8 -83 Q20 -78 28 -66" fill="none" stroke={p.hairLight} strokeWidth="3"/></g>:(g.flicks as Point[][]).map((a,i)=><polygon key={i} points={pts(a)} fill={p.hair} stroke="#161922" strokeWidth="1.2"/>)}</g>{!isN&&<Face author={author} expression={shot.expression} gaze={shot.actor.gaze??[0,0]} blink={blink} mouth={mouth}/>}
 </g></g></g>
}
