"""Reproduce the user-authorized EP08/EP09 sound pass from saved cue choices."""
import sys,json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'tools/storytime'))
from sfx_levels import pcm,choose_gain
from audio_mix import calibrate_mix
from sfx_assets import validate_asset
cat={a['id']:a for a in json.loads((R/'common/audio/sfx/sfx_catalog.json').read_text())['assets']}
def write(p,s):p.write_text(json.dumps(s,indent=2)+'\n')
def prepare(voice,id,at,dur,role):
 a=cat[id];validate_asset(a,R)
 dur=min(dur,a['duration_seconds']);g,m=choose_gain(R/a['relative_path'],voice,at,dur,role)
 return a,round(dur,6),g,m
p=R/'nemi/episodes/ep08_forced_bf_channel';plan=json.loads((p/'sfx_cues.json').read_text());cards=json.loads((p/'timing/ep08_timing.json').read_text())['cards'];voice=pcm(p/'audio/EP08_voice.wav')
# All cues land on the unchanged caption/action clock; dry ADB delivery stays distinct.
choices=[(0,'viral_whoosh',.575,'accent','Opening thought'),(3,'cartoon_pop_bubble_alert_01',.38,'accent','Channel reveal'),(5,'sting_question_chime_01',.49,'accent','Recall ADB'),(7,'cartoon_boing_bounce_01',.38,'hero','Old-design reveal'),(9,'viral_bruh',.817,'accent','Old version aside'),(10,'comedic_record_scratch_01',.8,'hero','Design rejection'),(11,'impact_wood_tap_01',.266,'surface','Character emphasis'),(13,'comedic_fail_low_tone_01',.9,'accent','Agreement with rejection'),(15,'ui_confirm_chime_01',.29,'accent','Decision'),(17,'paper_page_flip_03',.43,'surface','Fresh design sheet'),(18,'drawing_pencil_write_short_01',.9,'surface','New character art'),(19,'viral_a_few_moments_later',2.038,'surface','Work montage thought'),(21,'viral_anime_wow',2.5,'hero','Completed design reveal'),(23,'comedic_record_scratch_01',.65,'hero','Terrible idea reversal'),(25,'drawing_scratch_scribble_04',.325,'surface','Story animation aside'),(27,'sting_question_chime_02',.332,'accent','Ask the same of ADB'),(28,'viral_get_out',1.032,'hero','First rejection'),(29,'viral_pop',.72,'accent','Try again'),(30,'viral_bruh',.817,'hero','Second rejection'),(31,'cartoon_boing_metallic_01',.32,'accent','Persistence'),(33,'ui_confirm_chime_02',.539,'hero','Channel agreement'),(35,'viral_pop',.72,'accent','Nemi channel'),(36,'cartoon_pop_dry_01',.305,'accent','ADB channel'),(37,'paper_page_flip_03',.43,'surface','Two storytime channels'),(39,'sting_bell_dramatic_01',.65,'accent','Dangerous rivalry joke'),(41,'viral_bruh',.817,'accent','Annoy each other'),(44,'viral_ping',.5,'accent','Address ADB'),(45,'viral_whoosh',.575,'accent','Handoff'),(47,'cartoon_pop_dry_01',.305,'accent','ADB introduction'),(48,'paper_page_flip_03',.43,'surface','ADB stories'),(52,'viral_ping',.5,'accent','Dry oversharing confession'),(55,'ui_click_tactile_01',.1,'surface','Channel invitation'),(56,'ui_confirm_chime_01',.29,'accent','Link pointer'),(58,'sting_question_chime_02',.332,'accent','Nemi surprise'),(60,'viral_bruh',.817,'hero','Suspiciously normal reaction'),(64,'sting_achievement_bell_01',.8,'accent','Channel CTA'),(66,'impact_wood_tap_01',.266,'surface','Convincing effort'),(68,'viral_fahhh',1.47,'accent','Final plea')]
plan['events']=[]
for i,(n,id,dur,role,why) in enumerate(choices):
 c=cards[n];a,dur,g,m=prepare(voice,id,c['start'],dur,role)
 plan['events'].append({'event':f'ep08_sound_{i:02d}','card':n,'beat':c['beat'],'text':c['text'],'offset':0,'at':c['start'],'sfx_id':id,'file':'res://'+a['relative_path'],'duration':dur,'gain_db':g,'license':a['license'],'intent':why,'levels':m})
write(p/'sfx_cues.json',plan)
p=R/'nemi/episodes/ep09_sf_accident';s=json.loads((p/'scene.json').read_text());voice=pcm(R/s['audio'].removeprefix('res://'))
choices=[(.5,'viral_whoosh',.575,'accent','Wait / personal opening'),(3.839286,'sting_question_chime_01',.49,'accent','Terrifying / question mark'),(7.053571,'viral_bruh',.817,'hero','Normal / contradiction closeup'),(11.990435,'paper_page_flip_03',.43,'surface','San Francisco postcard'),(18.973043,'viral_anime_wow',2.5,'accent','Amazing'),(20.555652,'cartoon_boing_bounce_01',.38,'accent','Twenty thousand steps reveal'),(21.442609,'drawing_pencil_write_short_01',.65,'surface','Live underline'),(26.430909,'ui_confirm_chime_02',.539,'accent','Apple event'),(29.866667,'cartoon_digital_chirp_up_01',.549,'accent','2040'),(32.606364,'transition_camera_shutter_01',.351,'accent','Look at this view'),(37.539474,'sting_powerup_sparkle_02',.47,'accent','Waymo'),(40.557018,'viral_ping',.5,'accent','Autonomous'),(43.677719,'viral_bruh',.817,'accent','Empty driver seat'),(47.116316,'cartoon_digital_chirp_down_01',.522,'accent','Ghost metaphor'),(48.023158,'movement_cloth_rustle_02',.415,'surface','Clutching reaction'),(51.53193,'sting_bell_dramatic_01',.8,'hero','This is it / worried closeup'),(54.14087,'ui_confirm_chime_02',.539,'accent','Arrived safely'),(60.21087,'comedic_record_scratch_01',.65,'accent','Danger is behind me / foreshadowing'),(64.665217,'paper_page_flip_03',.43,'surface','Airport transition'),(67.96,'cartoon_twotone_alert_01',.724,'accent','Five minutes sign'),(75.391429,'whoosh_arrow_passby_01',.7,'accent','High speed'),(79.355714,'comedic_record_scratch_01',.85,'hero','Brakes / authored stop'),(81.070476,'ui_confirm_chime_01',.29,'accent','Stop in time'),(85.222857,'comedic_wrong_buzzer_01',.6,'hero','Definitely did not'),(86.839649,'impact_soft_heavy_01',.505,'hero','Rear bumper contact'),(86.839649,'impact_metal_clank_01',.272,'surface','Bumper contact metal accent'),(91.962456,'cartoon_slide_whistle_01',.45,'accent','Soul left my body'),(95.234286,'cartoon_twotone_alert_02',.731,'accent','Patrol arrival'),(99.299286,'ui_toggle_switch_01',.618,'surface','Flashlight inspection'),(100.317143,'paper_page_flip_03',.43,'surface','Statements'),(111.601304,'cartoon_digital_chirp_up_01',.549,'accent','Robot taxi callback'),(113.862174,'sting_achievement_bell_01',.8,'accent','Easy'),(115.114348,'viral_pop',.72,'accent','Normal cab callback'),(118.02,'viral_fahhh',1.749,'hero','Total disaster / final reversal')]
s['sfx']=[];s['events']=[e for e in s['events'] if not e['id'].startswith('sound_')];notes=[]
for i,(at,id,dur,role,why) in enumerate(choices):
 a,dur,g,m=prepare(voice,id,at,dur,role);event=f'sound_{i:02d}'
 s['events'].append({'id':event,'at':at,'intent':why})
 s['sfx'].append({'file':'res://'+a['relative_path'],'at':at,'duration':dur,'gain_db':g,'event':event})
 notes.append({'event':event,'at':at,'sfx_id':id,'duration':dur,'gain_db':g,'intent':why,'license':a['license'],'levels':m})
s['mix']=calibrate_mix(s,R);write(p/'scene.json',s)
write(p/'sound_plan.json',{'voice_sha256':hashlib.sha256((R/s['audio'].removeprefix('res://')).read_bytes()).hexdigest(),'notes':'Original narration and picture clock. Crying and post-payoff holds deliberately quiet. Exact existing root meme MP3 clips plus library recordings; no procedural substitutes or audio generation. Vocal clips are commentary accents, not a replacement character voice.','events':notes})
print('Sound cues: EP08',len(plan['events']),'EP09',len(notes))
for label,events in [('EP08',plan['events']),('EP09',notes)]:
 print(label,'quiet cues',[(e['sfx_id'],e['levels']['relative_rms_db']) for e in events if e['levels']['relative_rms_db'] < -18])
