class_name Episode08Subtitles
extends RefCounted

## Autogenerated Subtitles for Episode 08: "I FORCED MY BF TO CREATE A CHANNEL"
## Hard constraint: Strictly <= 5 words per card (100% verified)
## Total Cards: 69
## Total Duration: 95.405s

const SUBTITLES: Array[Dictionary] = [
	{"beat": 1, "speaker": "nemi", "start": 0.000, "end": 1.252, "text": "I have a new problem.", "mood": "shock"},
	{"beat": 1, "speaker": "nemi", "start": 1.635, "end": 2.991, "text": "I somehow convinced", "mood": "candid"},
	{"beat": 1, "speaker": "nemi", "start": 2.991, "end": 4.709, "text": "my boyfriend to start", "mood": "candid"},
	{"beat": 1, "speaker": "nemi", "start": 4.709, "end": 6.155, "text": "a YouTube channel.", "mood": "dread"},
	{"beat": 2, "speaker": "nemi", "start": 6.707, "end": 7.682, "text": "Guys...", "mood": "curious"},
	{"beat": 2, "speaker": "nemi", "start": 7.682, "end": 9.144, "text": "remember ADB?", "mood": "curious"},
	{"beat": 2, "speaker": "nemi", "start": 9.484, "end": 10.333, "text": "Yeah.", "mood": "normal"},
	{"beat": 2, "speaker": "nemi", "start": 10.333, "end": 11.607, "text": "THIS ADB.", "mood": "reveal"},
	{"beat": 2, "speaker": "nemi", "start": 12.032, "end": 12.813, "text": "...yeah.", "mood": "awkward"},
	{"beat": 2, "speaker": "nemi", "start": 12.813, "end": 13.891, "text": "This version.", "mood": "awkward"},
	{"beat": 3, "speaker": "nemi", "start": 14.359, "end": 15.385, "text": "ADB hated", "mood": "confession"},
	{"beat": 3, "speaker": "nemi", "start": 15.385, "end": 16.638, "text": "this character.", "mood": "confession"},
	{"beat": 3, "speaker": "nemi", "start": 17.021, "end": 18.554, "text": "Honestly...", "mood": "awkward"},
	{"beat": 3, "speaker": "nemi", "start": 18.554, "end": 20.428, "text": "I kinda understand why.", "mood": "sheepish"},
	{"beat": 4, "speaker": "nemi", "start": 21.108, "end": 21.899, "text": "So eventually", "mood": "thoughtful"},
	{"beat": 4, "speaker": "nemi", "start": 21.899, "end": 22.690, "text": "we decided:", "mood": "thoughtful"},
	{"beat": 4, "speaker": "nemi", "start": 22.930, "end": 23.863, "text": "okay.", "mood": "decisive"},
	{"beat": 4, "speaker": "nemi", "start": 23.863, "end": 24.796, "text": "We're making", "mood": "excited"},
	{"beat": 4, "speaker": "nemi", "start": 24.796, "end": 26.040, "text": "a completely new ADB.", "mood": "excited"},
	{"beat": 4, "speaker": "nemi", "start": 26.466, "end": 27.453, "text": "And after an", "mood": "tired"},
	{"beat": 4, "speaker": "nemi", "start": 27.453, "end": 29.180, "text": "unreasonable amount of work...", "mood": "tired"},
	{"beat": 4, "speaker": "nemi", "start": 29.180, "end": 30.578, "text": "we finally made one.", "mood": "proud"},
	{"beat": 5, "speaker": "nemi", "start": 31.129, "end": 31.991, "text": "And then I had", "mood": "smug"},
	{"beat": 5, "speaker": "nemi", "start": 31.991, "end": 32.925, "text": "another terrible idea.", "mood": "smug"},
	{"beat": 5, "speaker": "nemi", "start": 33.350, "end": 34.548, "text": "If I'm making", "mood": "explaining"},
	{"beat": 5, "speaker": "nemi", "start": 34.548, "end": 35.845, "text": "storytime animations...", "mood": "explaining"},
	{"beat": 5, "speaker": "nemi", "start": 35.845, "end": 37.142, "text": "why doesn't ADB make", "mood": "excited"},
	{"beat": 5, "speaker": "nemi", "start": 37.142, "end": 38.340, "text": "storytime animations too?", "mood": "excited"},
	{"beat": 6, "speaker": "nemi", "start": 38.808, "end": 39.833, "text": "ADB said no.", "mood": "deadpan"},
	{"beat": 6, "speaker": "nemi", "start": 40.173, "end": 41.012, "text": "I asked again.", "mood": "cheerful"},
	{"beat": 6, "speaker": "nemi", "start": 41.352, "end": 42.465, "text": "ADB said no.", "mood": "deadpan"},
	{"beat": 6, "speaker": "nemi", "start": 42.805, "end": 43.897, "text": "I asked again.", "mood": "cheerful"},
	{"beat": 6, "speaker": "nemi", "start": 44.535, "end": 45.578, "text": "And eventually...", "mood": "quiet"},
	{"beat": 6, "speaker": "nemi", "start": 45.578, "end": 47.019, "text": "ADB made a channel.", "mood": "victorious"},
	{"beat": 7, "speaker": "nemi", "start": 47.571, "end": 48.824, "text": "And now...", "mood": "proud"},
	{"beat": 7, "speaker": "nemi", "start": 48.824, "end": 50.328, "text": "there's Nemi...", "mood": "proud"},
	{"beat": 7, "speaker": "nemi", "start": 50.328, "end": 51.957, "text": "and there's ADB...", "mood": "proud"},
	{"beat": 7, "speaker": "nemi", "start": 51.957, "end": 53.837, "text": "both making storytime animations.", "mood": "excited"},
	{"beat": 7, "speaker": "nemi", "start": 54.262, "end": 55.997, "text": "Which is honestly...", "mood": "mischievous"},
	{"beat": 7, "speaker": "nemi", "start": 55.997, "end": 57.732, "text": "a little dangerous.", "mood": "mischievous"},
	{"beat": 7, "speaker": "nemi", "start": 58.114, "end": 59.270, "text": "Because now we can", "mood": "playful"},
	{"beat": 7, "speaker": "nemi", "start": 59.270, "end": 60.426, "text": "annoy each other with", "mood": "playful"},
	{"beat": 7, "speaker": "nemi", "start": 60.426, "end": 61.325, "text": "animation too.", "mood": "playful"},
	{"beat": 8, "speaker": "nemi", "start": 61.835, "end": 62.988, "text": "Actually...", "mood": "pivot"},
	{"beat": 8, "speaker": "nemi", "start": 62.988, "end": 64.141, "text": "ADB.", "mood": "call"},
	{"beat": 8, "speaker": "nemi", "start": 64.141, "end": 65.952, "text": "Introduce yourself.", "mood": "call"},
	{"beat": 8, "speaker": "adb", "start": 66.462, "end": 67.369, "text": "Uh...", "mood": "casual"},
	{"beat": 8, "speaker": "adb", "start": 67.369, "end": 68.622, "text": "I'm ADB.", "mood": "cool"},
	{"beat": 8, "speaker": "adb", "start": 69.022, "end": 69.944, "text": "I make storytime", "mood": "calm"},
	{"beat": 8, "speaker": "adb", "start": 69.944, "end": 70.942, "text": "animations too.", "mood": "calm"},
	{"beat": 8, "speaker": "adb", "start": 71.342, "end": 72.507, "text": "I talk about my", "mood": "conversational"},
	{"beat": 8, "speaker": "adb", "start": 72.507, "end": 73.505, "text": "own experiences...", "mood": "conversational"},
	{"beat": 8, "speaker": "adb", "start": 73.505, "end": 74.545, "text": "and probably overshare", "mood": "dry_smirk"},
	{"beat": 8, "speaker": "adb", "start": 74.545, "end": 75.502, "text": "way too much.", "mood": "dry_smirk"},
	{"beat": 8, "speaker": "adb", "start": 76.052, "end": 77.412, "text": "So... if you're curious,", "mood": "direct"},
	{"beat": 8, "speaker": "adb", "start": 77.412, "end": 78.772, "text": "check out my channel.", "mood": "direct"},
	{"beat": 8, "speaker": "adb", "start": 79.172, "end": 79.863, "text": "The link's in", "mood": "point_down"},
	{"beat": 8, "speaker": "adb", "start": 79.863, "end": 80.612, "text": "the description.", "mood": "point_down"},
	{"beat": 9, "speaker": "nemi", "start": 81.262, "end": 82.869, "text": "Wow.", "mood": "baffled"},
	{"beat": 9, "speaker": "nemi", "start": 82.869, "end": 84.369, "text": "That was", "mood": "baffled"},
	{"beat": 9, "speaker": "nemi", "start": 84.369, "end": 86.619, "text": "suspiciously normal.", "mood": "baffled"},
	{"beat": 9, "speaker": "nemi", "start": 87.087, "end": 88.327, "text": "Anyway... ADB is just", "mood": "warm"},
	{"beat": 9, "speaker": "nemi", "start": 88.327, "end": 89.257, "text": "getting started.", "mood": "warm"},
	{"beat": 9, "speaker": "nemi", "start": 89.257, "end": 90.187, "text": "So go check out", "mood": "supportive"},
	{"beat": 9, "speaker": "nemi", "start": 90.187, "end": 90.962, "text": "the channel.", "mood": "supportive"},
	{"beat": 9, "speaker": "nemi", "start": 91.388, "end": 92.358, "text": "I worked way too", "mood": "dramatic_tired"},
	{"beat": 9, "speaker": "nemi", "start": 92.358, "end": 93.005, "text": "hard to convince", "mood": "dramatic_tired"},
	{"beat": 9, "speaker": "nemi", "start": 93.005, "end": 93.544, "text": "this person.", "mood": "dramatic_tired"},
	{"beat": 9, "speaker": "nemi", "start": 93.926, "end": 94.725, "text": "Please make it worth it.", "mood": "pleading"}
]

static func get_cards_for_beat(beat_num: int) -> Array[Dictionary]:
	var res: Array[Dictionary] = []
	for c in SUBTITLES:
		if c.get("beat", 0) == beat_num:
			res.append(c)
	return res

static func get_all_cards() -> Array[Dictionary]:
	return SUBTITLES
