"""Record selected actual technical evidence; creative observations must be performed separately."""
from pathlib import Path
import json,datetime
ROOT=Path(__file__).resolve().parents[2];B=ROOT/'shorts/godot/upgrade02'
order=['my-song','wrong-class','quick-doodle','different-energy','act-natural','adb-big-idea','nemi-tiny-cat','duo-matching-moment']
observations={
'my-song':'Inspected headphone contact, real profile/back, shy-to-smile change, visible blink and full-body open-arm/thumb/heart gestures. Ending returns to the earcup with a semantic restart.',
'wrong-class':'Inspected collar/shades, full body and shoe crop, true profile/back, LAB3 doorway reveal, point/shrug/chin reactions and small farewell. No walking or door-opening contact is implied.',
'quick-doodle':'Inspected pencil-to-wrist and two-hand book grips, page doodles and cat book payoff, full-body grounding, close contact crops, profile/back and settled final page.',
'different-energy':'Inspected paired scale/eyelines, alternate singles/full body, paper/ink reversal legibility and earned ADB thumbs-up participation. Finale keeps both visible.',
'act-natural':'Inspected raised-phone grip, separate held photo plate, varied Nemi chin/hip/peace/heart/thumb poses and photographer blush reversal. Phone remains attached to its hand.',
'adb-big-idea':'Inspected sketch/pencil contact, chin/closed-eye brainfreeze, shrug/open hands, lightning/star thought change, true profile and small proud thumbs-up. No cat/book-show repetition.',
'nemi-tiny-cat':'Inspected moon→sleepy-cat wipe/match-cut, pointing eyeline, dream cloud/flower, profile/back and finger-heart ending. The cat is an external page doodle; no automatic book drawing/contact transfer is claimed.',
'duo-matching-moment':'Inspected Nemi-left/ADB-right paired layout, inward mirrored gestures/eyelines, overthinking reaction, shared heart, shutter and heart/star seal. No prop exchange or relationship-canon claim.'}
tracks={t['id']:t for t in json.loads((ROOT/'shorts/assets/music/batch01/catalog.json').read_text())}
entries=[];rows=[];musicrows=[]
for name in order:
 p=B/'productions'/name;c=json.loads((p/'short.json').read_text());r=p/'review';selected=json.loads((r/'current.json').read_text());rev=selected['revision'];tag=f'{c["id"]}_{rev}_1080x1920';movie=p/'renders'/f'{tag}.mp4'
 audio=json.loads((r/f'audio_{tag}.json').read_text());pace=json.loads((r/f'pacing_{tag}.json').read_text());export=json.loads((r/f'export_{tag}.json').read_text());assert audio['passed'] and pace['passed'] and movie.is_file()
 t=tracks[Path(c['music']['file']).stem];actions=sorted({q.get('action','rest') for a in c['actors'] for q in a['cues']});views=sorted({q.get('view','front') for a in c['actors'] for q in a['cues']})
 entry={'id':name,'title':c['title'],'cast':sorted({a['author'] for a in c['actors']}),'kind':'revised approved edit' if name in order[:5] else 'new skill demonstration','revision':rev,'movie':str(movie.relative_to(ROOT)),'movieSha256':export['sha256'],'specSha256':export['specSha256'],'frames':c['frames'],'duration':c['frames']/30,'shots':len(c['shots']),'visibleActions':actions,'views':views,'events':len(c['events']),'music':c['music'],'musicArtist':t['artist'],'musicTitle':t['title'],'musicSourceUrl':t['catalogUrl'],'technicalPassed':True,'maximumDecodedStaticSeconds':pace['maxStaticSeconds'],'audioCorrelation':audio['reconstructionCorrelation'],'truePeakDbTP':audio['loudness']['truePeakDbTP'],'observations':observations[name]}
 entries.append(entry);rows.append(f'| [{c["title"]}](../productions/{name}/review/QA.md) | {c["frames"]/30:g}s | {len(c["shots"])} | {len(actions)} | {pace["maxStaticSeconds"]:.3f}s | {audio["reconstructionCorrelation"]:.5f} | {audio["loudness"]["truePeakDbTP"]:.2f} |')
 musicrows.append(f'| {c["title"]} | {t["title"]} · {t["artist"]} | {c["music"]["sourceStart"]:.4f}–{c["music"]["sourceStart"]+c["music"]["duration"]:.4f}s | {c["music"]["gainDb"]:g}dB |')
 (r/'RENDERS.md').write_text(f'# Selected export\n\n[{tag}.mp4](../renders/{tag}.mp4) · {c["frames"]} frames / {c["frames"]/30:g}s ·1080×1920,30fps,H.264/AAC stereo48kHz.\n\nSource: [short.json](../short.json), [Edit.tscn](../Edit.tscn), [direction](../DIRECTION.md), [cue map](../CUE_MAP.json). Exact hashes and decoded checks are in the sibling reports. The original accepted batch01 movies remain separate history.\n')
 (r/'QA.md').write_text(f'# Export review · {c["title"]}\n\nNative Godot visual capture, exact {c["frames"]} encoded frames at30fps,1080×1920. All {len(c["shots"])-1} planned cuts have visible decoded changes at their named frame. Source/music hashes and ranges pass strict validation.\n\nLongest measured decoded still run: **{pace["maxStaticSeconds"]:.3f}s**, below1.5s. This is a pixel-change check, supported by performed art/contact observations below; it does not rate creativity.\n\nIndependent AAC reconstruction correlation **{audio["reconstructionCorrelation"]:.5f}**, measured delay {audio["delay"]["milliseconds"]:.4f}ms, true peak {audio["loudness"]["truePeakDbTP"]:.2f}dBTP, no clipped decoded samples, all {len(c["sfx"])} recorded SFX contributions verified. Original music version/hash/source section and cue map are retained. Sound measurement verifies exported sources; subjective listening taste is not claimed by numerical checks.\n\n{observations[name]} Godot still proofs/contact sheets and actual encoded first/final/cue frames were inspected. Native browser playback/seek observations are recorded separately in playback.json. The player was exercised at real speed with source audio enabled; this is separate from human creative acceptance.\n\nFinite VFX and motion are authored, completed paths stop, and the supported prop-contact drawings remain coherent at inspected boundaries. Supplemental visible art is separately authored Godot illustration; original hidden rig instances do not supply the visible lines.\n\nReports: [export](export.json), [audio](audio_{tag}.json), [pacing](pacing_{tag}.json), [current](current.json). All original storytime source/settings remain protected by the batch isolation audit.\n')
 (r/'current.json').write_text(json.dumps({**selected,'movie':str(movie.relative_to(ROOT)),'technicalPassed':True,'visualReview':'Godot proofs and actual encoded contact/cue/first/final frames inspected','playbackRecord':'playback.json'},indent=2)+'\n')
 if (p/'SKILL_USE.md').exists():
  s=(p/'SKILL_USE.md').read_text();s+='\n\n## Final exported evidence\n\nRoot completed the actual skill helper still/build path for revision'+rev+'. Strict validation, native Godot capture, encoded frame/cut checks, source music/SFX reconstruction and decoded pacing all passed. Godot proof and encoded contact sheets were inspected; details in [review/QA.md](review/QA.md), with native playback observations in review/playback.json. This supersedes the earlier source-stage pending status without pretending validation alone proved the finished picture.\n';(p/'SKILL_USE.md').write_text(s)
(B/'MANIFEST.json').write_text(json.dumps({'version':3,'generatedAtUTC':datetime.datetime.now(datetime.timezone.utc).isoformat(),'entries':entries},indent=2)+'\n')
(B/'review/QA.md').write_text('# Eight ink edits · checked exports\n\nFive revised approved ideas plus three new productions made through the ADB/Nemi/duo skills. All native1080×1920 at30fps, music-led without narration.\n\n| Short | Duration | Shots | Actions | Max still | Audio correlation | True peak dBTP |\n| --- | --- | --- | --- | --- | --- | --- |\n'+'\n'.join(rows)+'\n\nAll strict source/export/audio/pacing checks passed. Source frames are real Godot illustration, not generated bitmap assets or reference sprites. Each contact sheet and actual encoded first/final/cue frame was visually inspected; the16-action art sheets and intermediate hand/head/eye/contact phases were inspected in the Godot art pass. Native playback records are saved per production. No subjective human-listening or audience-performance guarantee is inferred from these checks.\n\nThe normal Godot loop counter sometimes underreports forced draw captures when desktop focus changes; actual raw/export frame decode, distinct cue images and exact encoded lengths are the frame authority. No missing frame validation is bypassed.\n\n18 validator/pacing regression tests passed. All three skills pass their metadata validators and use real scope-enforcing helpers. Skill forward tests corrected outdated routing/command examples; see ../SKILLS.md. Original1,081 editable storytime source/settings hashes remain unchanged, with only explicit new skills/routing status allowed.\n')
(B/'MUSIC_SECTIONS.md').write_text('# Exact music selections\n\nSource versions, URLs and original/decoded hashes: [five recording catalog](../../assets/music/batch01/MUSIC_SOURCES.md). Per-production short.json retains exact sourceHash, selected range and gain; CUE_MAP retains source clock musical accent evidence and purposes. These are approved famous/topic-fit recordings, without an invented current platform ranking.\n\n| Edit | Recording | Preview source range | Music gain |\n| --- | --- | --- | --- |\n'+'\n'.join(musicrows)+'\n\nOriginal recorded SFX are linked to named events and hashed in every spec; exported mix audibility is measured in each review/audio report. No synthesized SFX, voice/narration modification, pitch change or master EQ was added.\n')
(B/'README.md').write_text('# Eight dynamic Godot ink edits\n\n[Watch all eight](../../review/upgrade02/index.html) · [checks](review/QA.md) · [three skills](SKILLS.md) · [music sections](MUSIC_SECTIONS.md) · [direction](DIRECTION.md) · [isolation](review/ISOLATION.md).\n\nThe five existing ideas now have more visible poses, head/eye/hand motion, meaningful doodle/VFX events and varied14.5–18s runtimes. Three new Shorts demonstrate the solo ADB, solo Nemi and duo skills. Every export stays below the1.5s static limit; maximum across all eight is'+f'{max(x["maximumDecodedStaticSeconds"] for x in entries):.3f}s.\n\n'+'\n'.join(f'- [{x["title"]}](productions/{x["id"]}/review/RENDERS.md) · {x["duration"]:g}s · {x["kind"]}' for x in entries)+'\n\nThe authoritative workflow/schema are ../V3_WORKFLOW.md and ../V3_SCHEMA.md. Original episodes, rigs, voice identities and project settings are untouched. Accepted proof/batch01 are retained separately; rejected prototypes and obsolete renderer removed at the user’s request, recorded in review/legacy-cleanup.json. Source/music/QA are fully documented, with generated media local.\n')
print(f'Documented {len(entries)} exports; max still {max(x["maximumDecodedStaticSeconds"] for x in entries):.3f}s')
